// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Franchise.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Franchise
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: app-template-react/
// User:        2sic Web-Developer
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for Franchise 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Franchise data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Championships`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Franchise: AutoGenerated.ZAutoGenFranchise
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'Franchise' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFranchise: Custom.Data.CustomItem
  {
    /// <summary>
    /// Championships as int. <br/>
    /// To get other types use methods such as .Decimal("Championships")
    /// </summary>
    public int Championships => _item.Int("Championships");

    /// <summary>
    /// City as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("City", scrubHtml: true) etc.
    /// </summary>
    public string City => _item.String("City", fallback: "");

    /// <summary>
    /// Color as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Color", scrubHtml: true) etc.
    /// </summary>
    public string Color => _item.String("Color", fallback: "");

    /// <summary>
    /// Conference as single item of Conference.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type Conference was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public Conference Conference => _conference ??= _item.Child<Conference>("Conference");
    private Conference _conference;

    /// <summary>
    /// Logo as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Logo")
    /// </summary>
    public string Logo => _item.Url("Logo");

    /// <summary>
    /// Get the file object for Logo - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LogoFile => _item.File("Logo");

    /// <summary>
    /// Get the folder object for Logo.
    /// </summary>

    [JsonIgnore]
    public IFolder LogoFolder => _item.Folder("Logo");

    /// <summary>
    /// Name as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Name", scrubHtml: true) etc.
    /// </summary>
    public string Name => _item.String("Name", fallback: "");

    /// <summary>
    /// Stadium as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Stadium", scrubHtml: true) etc.
    /// </summary>
    public string Stadium => _item.String("Stadium", fallback: "");

    /// <summary>
    /// Website as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Website", scrubHtml: true) etc.
    /// </summary>
    public string Website => _item.String("Website", fallback: "");
  }
}